name: GitHub Release #change on correct name

on:
  push:
    branches: [ release ]

jobs:
  #change "project-release" on correct name
  Project-release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.MY_SECRET}}
          heroku_app_name: ${{secrets.SECRET_NAME}}
          heroku_email: ${{secrets.SECRET_EMAIL}}
          usedocker: true

      - name: Heroku login
        run: heroku login

      - name: Heroku container login
        run: heroku container:login

      - name: Build & Push image
        run: heroku container:push web --app git-hub-actions

      - name: Release
        run: heroku container:release web --app git-hub-actions