name: GitHub Staging Deploy

on: workflow_dispatch

jobs:
  Staging-deploy:
    name: "Build Container"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
      uses: actions/checkout@v2

      - run: echo "Staging has been successfully deployed"

#      - name: Heroku login
#      run: heroku login
#
#      - name: Heroku container login
#      run: heroku container:login
#
#      - name: build & push image
#      run: heroku container:push web --app git-hub-actions
#
#      - name: Release
#      run: heroku container:release web --app git-hub-actions